### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by eight04** [Moeriki/temporarily#2]
```
fs.js:167
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.rmdir (fs.js:810:14)
    at D:\Dev\config-locator\node_modules\temporarily\build\index.js:91:20
    at Array.forEach (<anonymous>)
    at process.cleanup (D:\Dev\config-locator\node_modules\temporarily\build\ind
ex.js:87:9)
    at process.emit (events.js:187:15)
    at processEmit [as emit] (D:\Dev\config-locator\node_modules\nyc\node_module
s\signal-exit\index.js:149:35)
```
It seems that it should use the synced version of `rmdir`:
https://github.com/Moeriki/temporarily/blob/44831a329368ac7456f459fa96d8b845f7ecfc0d/build/index.js#L91

node v10.4.1

**Comment by moeriki** [comment]
You're absolutely right.

Thanks for catching so many things. 👍
